[project]
name = "nhl-dbt-transform"
version = "0.1.0"
description = "dbt transformation layer for NHL data pipeline"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.10.15",
    "dbt-duckdb>=1.10.0",
    "dbt-postgres>=1.9.1",
]

[tool.ruff]
line-length = 100

